// <auto-generated />
namespace HeartOfGold.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditRequestStudNumberValidationFrom10To9Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditRequestStudNumberValidationFrom10To9Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201808201537390_EditRequestStudNumberValidationFrom10To9Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
